(IN-PACKAGE :DENSE-ARRAYS)
;;; This file is automatically managed by (DEFTYPE ARRAY ...) and
;;; ENSURE-ARRAY-TYPE-DURING-LOAD. Please do not modify this file manually.

(PROGN
 (PUSH '(ARRAY SINGLE-FLOAT) *ARRAY-TYPES*)
 (TYPE-EXPAND '(ARRAY SINGLE-FLOAT)))
(PROGN
 (PUSH '(ARRAY SINGLE-FLOAT 2) *ARRAY-TYPES*)
 (TYPE-EXPAND '(ARRAY SINGLE-FLOAT 2)))
(PROGN
 (PUSH '(ARRAY (INTEGER -2147483648 2147483647)) *ARRAY-TYPES*)
 (TYPE-EXPAND '(ARRAY (INTEGER -2147483648 2147483647))))
(PROGN (PUSH '(ARRAY BIT) *ARRAY-TYPES*) (TYPE-EXPAND '(ARRAY BIT)))
(PROGN
 (PUSH '(ARRAY (INTEGER -32768 32767)) *ARRAY-TYPES*)
 (TYPE-EXPAND '(ARRAY (INTEGER -32768 32767))))
(PROGN
 (PUSH '(ARRAY (INTEGER -128 127)) *ARRAY-TYPES*)
 (TYPE-EXPAND '(ARRAY (INTEGER -128 127))))
