(IN-PACKAGE :DENSE-ARRAYS)
;;; This file is automatically managed by (DEFTYPE ARRAY ...) and
;;; ENSURE-ARRAY-TYPE-DURING-LOAD. Please do not modify this file manually.

(PROGN
 (PUSH '(ARRAY SINGLE-FLOAT) *ARRAY-TYPES-CACHE*)
 (TYPE-EXPAND '(ARRAY SINGLE-FLOAT)))
(PROGN
 (PUSH '(ARRAY SINGLE-FLOAT 2) *ARRAY-TYPES-CACHE*)
 (TYPE-EXPAND '(ARRAY SINGLE-FLOAT 2)))
(PROGN
 (PUSH '(ARRAY (INTEGER -2147483648 2147483647)) *ARRAY-TYPES-CACHE*)
 (TYPE-EXPAND '(ARRAY (INTEGER -2147483648 2147483647))))
(PROGN (PUSH '(ARRAY BIT) *ARRAY-TYPES-CACHE*) (TYPE-EXPAND '(ARRAY BIT)))
(PROGN
 (PUSH '(ARRAY DOUBLE-FLOAT) *ARRAY-TYPES-CACHE*)
 (TYPE-EXPAND '(ARRAY DOUBLE-FLOAT)))
(PROGN (PUSH '(ARRAY (INTEGER 0 1)) *ARRAY-TYPES-CACHE*) (TYPE-EXPAND '(ARRAY (INTEGER 0 1))))
